// Next
import type { Metadata } from 'next'

// Providers
import { Providers } from '@/app/providers'

// Styles
import '@/styles/tailwind.css'


export const metadata: Metadata = {
    title: 'Clips AI Demo',
    description: 'a UI demo of the clips generated by the clipsai library',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" className="h-full" suppressHydrationWarning>
            <body className="flex min-h-full flex-col bg-white dark:bg-zinc-900">
                <Providers>
                    <main className="flex-1">
                        <div className="mx-auto py-6 px-4 sm:px-6 md:px-8">
                            {children}
                        </div>
                    </main>
                </Providers>
            </body>
        </html>
    )
}
